# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help_plz', '0004_auto_20170613_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='helprequest',
            name='concurers',
            field=models.ManyToManyField(
                related_name='concurers', to=settings.AUTH_USER_MODEL),
        ),
    ]
