# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('help_plz', '0005_helprequest_concurers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.ManyToManyField(related_name='students_set', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(related_name='teacher_set', to=settings.AUTH_USER_MODEL)),
                ('tutors', models.ManyToManyField(related_name='tutor_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
