# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_plz', '0007_helprequest_klass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helprequest',
            name='klass',
            field=models.ForeignKey(
                default=37, on_delete=django.db.models.deletion.CASCADE, to='help_plz.Class'),
        ),
    ]
