# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_plz', '0008_auto_20170615_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='class_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='teachers',
            field=models.ManyToManyField(related_name='teaching_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='tutors',
            field=models.ManyToManyField(related_name='tutoring_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='klass',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='help_plz.Class'),
        ),
    ]
