# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_plz', '0009_auto_20170615_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='default_name', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='student_password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AddField(
            model_name='class',
            name='tutor_password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='klass',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='help_plz.Class'),
        ),
    ]
