# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_plz', '0010_auto_20170615_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(default='default_name', max_length=50, unique=True),
        ),
    ]
