# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_plz', '0011_auto_20170615_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={},
        ),
    ]
